services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./data/qdrant:/qdrant/storage
#  localllm:
#    build:
#      dockerfile: Dockerfile
#    container_name: localllm
#    volumes:
#      - ./data:/data
configs:
  qdrant_config:
    content: |
      log_level: INFO
