version: "3"

tasks:
  format:
    desc: Format python code with ruff
    cmd: uv run --only-dev ruff format src tests
  lint:
    desc: Lint python code with ruff
    cmd: uv run --only-dev ruff check src tests
  run:
    desc: run the app
    cmd: uv run --only-dev localllm
  test:
    desc: run tests
    cmd: uv run --only-dev pytest
  start-qdrant:
    desc: Start qdrant
    cmd: docker compose up -d qdrant
  stop-qdrant:
    desc: Stop qdrant
    cmd: docker compose down qdrant
  default:
    desc: List all tasks and their descriptions
    cmd: task --list-all
