name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --all-extras --group dev --group test
      - name: Test
        run: uv run pytest tests
      - name: lint
        run: uv run ruff check autobot tests
      - name: format
        run: uv run ruff format --check autobot tests
